# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

#### 2.Создать вектор размера 100, заполненный единицами

In [89]:
first = np.full(100, 1)
print(first)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
third = np.full(100, 3)
print(third)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

#### 5. Поменять 2 строки в матрице

In [5]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
matrix[[0,2]] = matrix[[2,0]]
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


#### 6. Создать вектор со значениями от 10 до 100

In [6]:
vector = np.arange(10,100)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 7. Развернуть вектор (первый становится последним)

In [7]:
vector = vector[::-1]
print(vector)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [8]:
matrix4x4 = np.arange(16).reshape(4,4)
print(matrix4x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [9]:
vector = np.arange(1,6)
print(vector)
nv = 3
v0 = np.zeros(len(vector) + (len(vector)-1)*(nv))
print(v0)
v0[::nv+1] = vector
print(v0)

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 10. Создать 3x3 единичную матрицу

In [10]:
matrix = np.eye(3,3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [13]:
array = np.random.random((3,3,3))
print(array)

[[[0.43722375 0.14747863 0.48072052]
  [0.13815653 0.31870816 0.54923908]
  [0.42909457 0.25973699 0.3611743 ]]

 [[0.54771092 0.50333729 0.34273716]
  [0.39552863 0.7159465  0.23698169]
  [0.44022563 0.33858249 0.92188121]]

 [[0.15165888 0.71613939 0.15826559]
  [0.3428411  0.34641084 0.67891592]
  [0.88683748 0.88846164 0.47739051]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [15]:
array = np.random.random((10,10))
arrayMin, arrayMax = array.min(), array.max()
print(arrayMin, arrayMax)

0.007486261566466923 0.9937077835973783


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
vector = np.random.full(30)
print(vector)

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [22]:
matrix = np.ones((10,10))
matrix[1:9,1:9] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [56]:
diag = [1,2,2,4]
array = np.diag(diag, k=0)
print(array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 4]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [57]:
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [59]:
index = np.unravel_index(100, (6,7,8))
print(index)

(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [60]:
matrix = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [66]:
matrixFirst = np.ones((5,3))
matrixSecond = np.ones((3,2))
print(np.dot(matrixFirst, matrixSecond))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [68]:
array = np.arange(11)
array[(3 < array) & (array <= 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [77]:
array = np.zeros((5,5))
array += np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

NameError: name 'xrange' is not defined

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [87]:
vector = np.linspace(0,1,12)[1:11]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [90]:
vector = np.random.random(10)
vector.sort()
print(vector)

[0.11831527 0.13762505 0.16118122 0.21907414 0.28891088 0.33070378
 0.47225593 0.74149625 0.74718252 0.79595213]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [96]:
first = np.random.choice(10, 10, replace=False)
second = np.random.choice(10, 10, replace=False)
equal = np.allclose(first,second)
print(equal)

[25 44 78 38 64 90 65 12 52 49 79 95 75 17 47 50 32 40 15 14  5  6 55  4
 28 46  1 42 26 36 87 77 35 85 67 92 91 62  2  0 33 88 98  3 72 27 39 94
 81 86 30 56 82 83 73 93 80 48 58 84 53 45 16 63 51 13 69 89 34 99 23 19
 74 68 97 76 11 24 37 57 31 29  7  8 20 70 61 60 66 54 43 41 96 59 21 10
 18 71 22  9]
False


#### 28. Сделать массив неизменяемым

In [100]:
array = np.random.choice(10, 10, replace=False)
array.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [103]:
array = np.random.choice(100, 100, replace=False)
np.random.shuffle(array)
n = 5

print (array[np.argpartition(-array,n)[:n]])

[97 98 99 95 96]


#### 30. Заменить максимальный элемент на ноль

In [104]:
array = np.random.choice(100, 100, replace=False)
array[array.argmax()] = 0
print(array)

[14 65 80 33 68 82 87 64 90 10 23 16 93 45 28 72 84 11 57 94 79 61 22 18
 17 24  0 92 15 35 42 25 52 49 51 40  0 58 59 30 98 20 67 54 66 48 39 83
 29 50 75 32  5 91  6 44 69 77 74 85  3 86 89  8 95 88 73 38 97 36 13  2
 70  7 37 46 47 27 41 55 19 12 26 56 71 21  1 63 60 31 76 78 81 53 43 34
 62  4 96  9]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [108]:
array = np.zeros((10,10), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(array)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [122]:
arrayFirst = np.array([1,2,3,4]) 
arraySecond = np.array([5,6,7]) 
lenFirst = len(arrayFirst)
lenSecond = len(arraySecond)
xm = np.repeat(arrayFirst,lenSecond)
ym = np.tile(arraySecond,lenFirst)
cauchym = (1.0/(xm-ym)).reshape([lenFirst,lenSecond]);
print(cauchym)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [123]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 34. Напечатать все значения в массиве

In [132]:
import sys
np.set_printoptions(threshold=sys.maxsize)
array = np.zeros((10,10))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [134]:
array = np.arange(100)
value = np.random.uniform(0,100)
index = (np.abs(array-value)).argmin()
print(array[index])

86


#### 36. Преобразовать массив из float в int

In [136]:
array = np.arange(10, dtype=np.int32)
array = array.astype(np.float32, copy=False)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [137]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(array.shape):
    print(index, array[index])

(0,) 4
(1,) 7
(2,) 8
(3,) 2
(4,) 9
(5,) 6
(6,) 5
(7,) 0
(8,) 1
(9,) 3
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [138]:
n = 10
p = 3
array = np.zeros((n,n))
np.put(array, np.random.choice(range(n*n), p, replace=False), 1)

#### 39. Отнять среднее из каждой строки в матрице

In [145]:
matrix = np.random.rand(3, 2)
matrix2 = matrix - matrix.mean(axis=1, keepdims=True)
print(matrix2)

[[ 0.09909579 -0.09909579]
 [ 0.13002247 -0.13002247]
 [-0.29941272  0.29941272]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [148]:
n = 2
matrix = np.random.randint(low=1, high=100, size=[4,4])
print(matrix[matrix[:,n].argsort()])

[[72 24 15 42]
 [92 74 18 70]
 [ 7 11 52 70]
 [75 19 77 52]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [149]:
array = np.random.randint(0,3,(3,10))
print((~array.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [150]:
arrayFirst = np.ones(10)
arraySecond = np.random.randint(0,len(Z),20)
arrayFirst += np.bincount(arraySecond, minlength=len(Z))
print(arrayFirst)

[4. 2. 1. 5. 3. 1. 6. 2. 2. 4.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [152]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [153]:
array = np.random.randint(0,10, (3,4,3,4))
sum = array.reshape(array.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 48 52 65]
 [64 50 70 49]
 [61 50 67 55]]
